import { University, Scholarship } from './types';

export const universities: University[] = [
  {
    id: 'uni-1',
    name: 'Technical University of Munich',
    country: 'Germany',
    city: 'Munich',
    websiteUrl: 'https://www.tum.de',
    logoUrl: '/logos/tum.png',
    rankingQs: 37,
    rankingThe: 30,
    estimatedMonthlyLivingCostEur: 950,
    description: 'TU Munich is one of Europe\'s top technical universities, renowned for engineering, computer science, and natural sciences. As a public university in Bavaria, it offers tuition-free education for all students.',
    programs: [
      {
        id: 'prog-1',
        universityId: 'uni-1',
        name: 'M.Sc. Informatics',
        fieldOfStudy: 'Computer Science',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 0,
        minGpaRequired: 3.5,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'B2',
        applicationDeadline: '2025-10-15',
        applicationUrl: 'https://www.tum.de/apply',
        additionalRequirements: 'GRE recommended, motivation letter, 2 recommendation letters'
      },
      {
        id: 'prog-2',
        universityId: 'uni-1',
        name: 'M.Sc. Data Engineering and Analytics',
        fieldOfStudy: 'Computer Science',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 0,
        minGpaRequired: 3.3,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'B2',
        applicationDeadline: '2025-10-15',
        applicationUrl: 'https://www.tum.de/apply',
      },
      {
        id: 'prog-3',
        universityId: 'uni-1',
        name: 'B.Sc. Mechanical Engineering',
        fieldOfStudy: 'Engineering',
        degreeLevel: 'bachelors',
        languageOfInstruction: 'German',
        durationMonths: 36,
        tuitionPerYearEur: 0,
        minGpaRequired: 3.0,
        requiredLanguage: 'German',
        requiredLanguageLevel: 'C1',
        applicationDeadline: '2025-07-15',
        applicationUrl: 'https://www.tum.de/apply',
      }
    ]
  },
  {
    id: 'uni-2',
    name: 'Delft University of Technology',
    country: 'Netherlands',
    city: 'Delft',
    websiteUrl: 'https://www.tudelft.nl',
    logoUrl: '/logos/tudelft.png',
    rankingQs: 47,
    rankingThe: 48,
    estimatedMonthlyLivingCostEur: 1100,
    description: 'TU Delft is the largest and oldest Dutch public technical university. Known for architecture, aerospace, and computer science with a strong international community.',
    programs: [
      {
        id: 'prog-4',
        universityId: 'uni-2',
        name: 'M.Sc. Computer Science',
        fieldOfStudy: 'Computer Science',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 2314,
        minGpaRequired: 3.3,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'C1',
        applicationDeadline: '2025-12-01',
        applicationUrl: 'https://www.tudelft.nl/apply',
      },
      {
        id: 'prog-5',
        universityId: 'uni-2',
        name: 'M.Sc. Aerospace Engineering',
        fieldOfStudy: 'Engineering',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 2314,
        minGpaRequired: 3.0,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'C1',
        applicationDeadline: '2025-12-01',
        applicationUrl: 'https://www.tudelft.nl/apply',
      }
    ]
  },
  {
    id: 'uni-3',
    name: 'RWTH Aachen University',
    country: 'Germany',
    city: 'Aachen',
    websiteUrl: 'https://www.rwth-aachen.de',
    logoUrl: '/logos/rwth.png',
    rankingQs: 106,
    rankingThe: 90,
    estimatedMonthlyLivingCostEur: 850,
    description: 'RWTH Aachen is one of Germany\'s Universities of Excellence and the largest technical university in Germany. Known for engineering and computer science programs with strong industry connections.',
    programs: [
      {
        id: 'prog-6',
        universityId: 'uni-3',
        name: 'M.Sc. Computer Science',
        fieldOfStudy: 'Computer Science',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 0,
        minGpaRequired: 3.0,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'B2',
        applicationDeadline: '2026-03-01',
        applicationUrl: 'https://www.rwth-aachen.de/apply',
      },
      {
        id: 'prog-7',
        universityId: 'uni-3',
        name: 'M.Sc. Electrical Engineering',
        fieldOfStudy: 'Engineering',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 0,
        minGpaRequired: 2.8,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'B2',
        applicationDeadline: '2026-03-01',
        applicationUrl: 'https://www.rwth-aachen.de/apply',
      }
    ]
  },
  {
    id: 'uni-4',
    name: 'University of Amsterdam',
    country: 'Netherlands',
    city: 'Amsterdam',
    websiteUrl: 'https://www.uva.nl',
    logoUrl: '/logos/uva.png',
    rankingQs: 53,
    rankingThe: 60,
    estimatedMonthlyLivingCostEur: 1200,
    description: 'The University of Amsterdam is the largest university in the Netherlands by enrollment. Known for social sciences, humanities, and AI research. Vibrant international student community.',
    programs: [
      {
        id: 'prog-8',
        universityId: 'uni-4',
        name: 'M.Sc. Artificial Intelligence',
        fieldOfStudy: 'Computer Science',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 2314,
        minGpaRequired: 3.4,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'C1',
        applicationDeadline: '2025-12-15',
        applicationUrl: 'https://www.uva.nl/apply',
      },
      {
        id: 'prog-9',
        universityId: 'uni-4',
        name: 'M.Sc. Business Administration',
        fieldOfStudy: 'Business Administration',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 12,
        tuitionPerYearEur: 2314,
        minGpaRequired: 3.2,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'C1',
        applicationDeadline: '2025-11-01',
        applicationUrl: 'https://www.uva.nl/apply',
      }
    ]
  },
  {
    id: 'uni-5',
    name: 'KTH Royal Institute of Technology',
    country: 'Sweden',
    city: 'Stockholm',
    websiteUrl: 'https://www.kth.se',
    logoUrl: '/logos/kth.png',
    rankingQs: 73,
    rankingThe: 72,
    estimatedMonthlyLivingCostEur: 1050,
    description: 'KTH is Sweden\'s largest and most prestigious technical university. Offers tuition-free education for EU/EEA students and world-class engineering and technology programs.',
    programs: [
      {
        id: 'prog-10',
        universityId: 'uni-5',
        name: 'M.Sc. Computer Science and Engineering',
        fieldOfStudy: 'Computer Science',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 0,
        minGpaRequired: 3.2,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'B2',
        applicationDeadline: '2026-01-15',
        applicationUrl: 'https://www.kth.se/apply',
      }
    ]
  },
  {
    id: 'uni-6',
    name: 'ETH Zurich',
    country: 'Switzerland',
    city: 'Zurich',
    websiteUrl: 'https://ethz.ch',
    logoUrl: '/logos/ethz.png',
    rankingQs: 7,
    rankingThe: 11,
    estimatedMonthlyLivingCostEur: 1800,
    description: 'ETH Zurich is one of the world\'s leading universities for technology and natural sciences. Albert Einstein\'s alma mater, consistently ranked among the top 10 globally.',
    programs: [
      {
        id: 'prog-11',
        universityId: 'uni-6',
        name: 'M.Sc. Computer Science',
        fieldOfStudy: 'Computer Science',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 1460,
        minGpaRequired: 3.7,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'C1',
        applicationDeadline: '2025-12-15',
        applicationUrl: 'https://ethz.ch/apply',
      }
    ]
  },
  {
    id: 'uni-7',
    name: 'Technical University of Berlin',
    country: 'Germany',
    city: 'Berlin',
    websiteUrl: 'https://www.tu.berlin',
    logoUrl: '/logos/tuberlin.png',
    rankingQs: 154,
    rankingThe: 140,
    estimatedMonthlyLivingCostEur: 900,
    description: 'TU Berlin is a research university in the heart of Berlin. One of the largest and most prestigious technical universities in Germany with strong international programs.',
    programs: [
      {
        id: 'prog-12',
        universityId: 'uni-7',
        name: 'M.Sc. Computer Science',
        fieldOfStudy: 'Computer Science',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 0,
        minGpaRequired: 3.3,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'B2',
        applicationDeadline: '2025-12-15',
        applicationUrl: 'https://www.tu.berlin/apply',
      }
    ]
  },
  {
    id: 'uni-8',
    name: 'University of Vienna',
    country: 'Austria',
    city: 'Vienna',
    websiteUrl: 'https://www.univie.ac.at',
    logoUrl: '/logos/univie.png',
    rankingQs: 130,
    rankingThe: 124,
    estimatedMonthlyLivingCostEur: 900,
    description: 'The University of Vienna is one of the oldest and largest universities in Europe, founded in 1365. Offers affordable education in a beautiful city consistently ranked as the world\'s most liveable.',
    programs: [
      {
        id: 'prog-13',
        universityId: 'uni-8',
        name: 'M.Sc. Computer Science',
        fieldOfStudy: 'Computer Science',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 726,
        minGpaRequired: 3.0,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'B2',
        applicationDeadline: '2026-02-28',
        applicationUrl: 'https://www.univie.ac.at/apply',
      },
      {
        id: 'prog-14',
        universityId: 'uni-8',
        name: 'M.Sc. Business Informatics',
        fieldOfStudy: 'Business Administration',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 726,
        minGpaRequired: 3.0,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'B2',
        applicationDeadline: '2026-02-28',
        applicationUrl: 'https://www.univie.ac.at/apply',
      }
    ]
  },
  {
    id: 'uni-9',
    name: 'Charles University',
    country: 'Czech Republic',
    city: 'Prague',
    websiteUrl: 'https://cuni.cz',
    logoUrl: '/logos/cuni.png',
    rankingQs: 246,
    rankingThe: 236,
    estimatedMonthlyLivingCostEur: 650,
    description: 'Charles University is the oldest and largest university in the Czech Republic (founded 1348). Prague offers one of the most affordable living costs among European capitals.',
    programs: [
      {
        id: 'prog-15',
        universityId: 'uni-9',
        name: 'M.Sc. Computer Science',
        fieldOfStudy: 'Computer Science',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 5000,
        minGpaRequired: 2.8,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'B2',
        applicationDeadline: '2026-04-30',
        applicationUrl: 'https://cuni.cz/apply',
      }
    ]
  },
  {
    id: 'uni-10',
    name: 'Politecnico di Milano',
    country: 'Italy',
    city: 'Milan',
    websiteUrl: 'https://www.polimi.it',
    logoUrl: '/logos/polimi.png',
    rankingQs: 123,
    rankingThe: 155,
    estimatedMonthlyLivingCostEur: 1000,
    description: 'Politecnico di Milano is Italy\'s most prestigious technical university. Known for engineering, architecture, and design with competitive tuition and merit-based fee waivers.',
    programs: [
      {
        id: 'prog-16',
        universityId: 'uni-10',
        name: 'M.Sc. Computer Science and Engineering',
        fieldOfStudy: 'Computer Science',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 3900,
        minGpaRequired: 3.0,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'B2',
        applicationDeadline: '2026-01-20',
        applicationUrl: 'https://www.polimi.it/apply',
      }
    ]
  },
  {
    id: 'uni-11',
    name: 'University of Helsinki',
    country: 'Finland',
    city: 'Helsinki',
    websiteUrl: 'https://www.helsinki.fi',
    logoUrl: '/logos/uhelsinki.png',
    rankingQs: 115,
    rankingThe: 101,
    estimatedMonthlyLivingCostEur: 1000,
    description: 'The University of Helsinki is Finland\'s leading multidisciplinary research university. Finland offers a welcoming environment for international students with strong tech and innovation ecosystems.',
    programs: [
      {
        id: 'prog-17',
        universityId: 'uni-11',
        name: 'M.Sc. Computer Science',
        fieldOfStudy: 'Computer Science',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 15000,
        minGpaRequired: 3.2,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'B2',
        applicationDeadline: '2026-01-10',
        applicationUrl: 'https://www.helsinki.fi/apply',
      }
    ]
  },
  {
    id: 'uni-12',
    name: 'University of Warsaw',
    country: 'Poland',
    city: 'Warsaw',
    websiteUrl: 'https://www.uw.edu.pl',
    logoUrl: '/logos/uw.png',
    rankingQs: 262,
    rankingThe: 401,
    estimatedMonthlyLivingCostEur: 600,
    description: 'The University of Warsaw is Poland\'s top-ranked university. Warsaw offers very affordable living costs with a rapidly growing tech scene and vibrant student life.',
    programs: [
      {
        id: 'prog-18',
        universityId: 'uni-12',
        name: 'M.Sc. Computer Science',
        fieldOfStudy: 'Computer Science',
        degreeLevel: 'masters',
        languageOfInstruction: 'English',
        durationMonths: 24,
        tuitionPerYearEur: 3200,
        minGpaRequired: 2.7,
        requiredLanguage: 'English',
        requiredLanguageLevel: 'B2',
        applicationDeadline: '2026-06-15',
        applicationUrl: 'https://www.uw.edu.pl/apply',
      }
    ]
  }
];

export const scholarships: Scholarship[] = [
  {
    id: 'sch-1',
    name: 'DAAD Scholarship',
    provider: 'German Academic Exchange Service (DAAD)',
    type: 'stipend',
    amountDescription: '€934/month + travel + insurance',
    amountEurMonthly: 934,
    coverage: 'Monthly stipend of €934, travel allowance, health insurance, study and research allowance',
    eligibilityNationalities: 'all',
    eligibilityMinGpa: 3.0,
    eligibilityFields: 'all',
    eligibilityDegreeLevels: ['masters', 'phd'],
    eligibilityOther: 'Relevant professional experience preferred, no more than 6 years since last degree',
    applicationDeadline: '2025-10-15',
    applicationUrl: 'https://www.daad.de/scholarships',
    linkedUniversityIds: ['uni-1', 'uni-3', 'uni-7']
  },
  {
    id: 'sch-2',
    name: 'Holland Scholarship',
    provider: 'Dutch Ministry of Education',
    type: 'partial',
    amountDescription: '€5,000 one-time grant',
    amountEurMonthly: 417,
    coverage: 'One-time grant of €5,000 for the first year of studies',
    eligibilityNationalities: 'all',
    eligibilityMinGpa: 3.0,
    eligibilityFields: 'all',
    eligibilityDegreeLevels: ['bachelors', 'masters'],
    eligibilityOther: 'Non-EEA students only, first time studying in the Netherlands',
    applicationDeadline: '2026-02-01',
    applicationUrl: 'https://www.studyinholland.nl/finances/scholarships',
    linkedUniversityIds: ['uni-2', 'uni-4']
  },
  {
    id: 'sch-3',
    name: 'Erasmus Mundus Joint Masters',
    provider: 'European Commission',
    type: 'full_tuition',
    amountDescription: 'Full tuition + €1,400/month stipend',
    amountEurMonthly: 1400,
    coverage: 'Full tuition, monthly stipend of €1,400, travel costs, insurance, installation costs',
    eligibilityNationalities: 'all',
    eligibilityMinGpa: 3.2,
    eligibilityFields: 'all',
    eligibilityDegreeLevels: ['masters'],
    applicationDeadline: '2026-01-10',
    applicationUrl: 'https://erasmus-plus.ec.europa.eu',
    linkedUniversityIds: ['uni-1', 'uni-2', 'uni-5', 'uni-10']
  },
  {
    id: 'sch-4',
    name: 'Stipendium Hungaricum',
    provider: 'Hungarian Government',
    type: 'full_tuition',
    amountDescription: 'Full tuition + €140/month stipend + accommodation',
    amountEurMonthly: 140,
    coverage: 'Full tuition waiver, monthly stipend, dormitory accommodation or housing allowance',
    eligibilityNationalities: ['Pakistan', 'India', 'Bangladesh', 'Nigeria', 'Egypt', 'Turkey', 'Jordan', 'Kenya', 'Ghana', 'Ethiopia'],
    eligibilityMinGpa: 2.8,
    eligibilityFields: 'all',
    eligibilityDegreeLevels: ['bachelors', 'masters', 'phd'],
    applicationDeadline: '2026-01-15',
    applicationUrl: 'https://stipendiumhungaricum.hu',
    linkedUniversityIds: []
  },
  {
    id: 'sch-5',
    name: 'Swedish Institute Scholarship',
    provider: 'Swedish Institute',
    type: 'full_tuition',
    amountDescription: 'Full tuition + SEK 10,000/month (~€900)',
    amountEurMonthly: 900,
    coverage: 'Full tuition waiver, monthly living allowance, travel grant, insurance',
    eligibilityNationalities: ['Pakistan', 'India', 'Bangladesh', 'Nigeria', 'Egypt', 'Kenya', 'Ghana', 'Ethiopia', 'Turkey'],
    eligibilityMinGpa: 3.0,
    eligibilityFields: 'all',
    eligibilityDegreeLevels: ['masters'],
    eligibilityOther: 'Minimum 3,000 hours of work experience, demonstrated leadership',
    applicationDeadline: '2026-02-10',
    applicationUrl: 'https://si.se/en/apply/scholarships',
    linkedUniversityIds: ['uni-5']
  },
  {
    id: 'sch-6',
    name: 'Deutschlandstipendium',
    provider: 'German Federal Government + Private Sponsors',
    type: 'stipend',
    amountDescription: '€300/month stipend',
    amountEurMonthly: 300,
    coverage: 'Monthly stipend of €300 for at least two semesters, networking events',
    eligibilityNationalities: 'all',
    eligibilityMinGpa: 3.3,
    eligibilityFields: 'all',
    eligibilityDegreeLevels: ['bachelors', 'masters'],
    applicationDeadline: '2025-09-30',
    applicationUrl: 'https://www.deutschlandstipendium.de',
    linkedUniversityIds: ['uni-1', 'uni-3', 'uni-7']
  },
  {
    id: 'sch-7',
    name: 'OeAD Scholarship (Austria)',
    provider: 'Austrian Agency for International Cooperation',
    type: 'stipend',
    amountDescription: '€1,250/month stipend',
    amountEurMonthly: 1250,
    coverage: 'Monthly stipend, tuition fee waiver at Austrian universities, health insurance',
    eligibilityNationalities: 'all',
    eligibilityMinGpa: 3.0,
    eligibilityFields: 'all',
    eligibilityDegreeLevels: ['masters', 'phd'],
    applicationDeadline: '2026-03-01',
    applicationUrl: 'https://oead.at/scholarships',
    linkedUniversityIds: ['uni-8']
  },
  {
    id: 'sch-8',
    name: 'ETH Zurich Excellence Scholarship',
    provider: 'ETH Zurich Foundation',
    type: 'full_tuition',
    amountDescription: 'Full tuition + CHF 12,000/semester stipend',
    amountEurMonthly: 2000,
    coverage: 'Full tuition waiver plus living and study stipend of CHF 12,000 per semester',
    eligibilityNationalities: 'all',
    eligibilityMinGpa: 3.8,
    eligibilityFields: 'all',
    eligibilityDegreeLevels: ['masters'],
    eligibilityOther: 'Top 10% of graduating class, outstanding academic achievements',
    applicationDeadline: '2025-12-15',
    applicationUrl: 'https://ethz.ch/scholarships',
    linkedUniversityIds: ['uni-6']
  },
  {
    id: 'sch-9',
    name: 'Politecnico di Milano Merit Scholarship',
    provider: 'Politecnico di Milano',
    type: 'partial',
    amountDescription: '€10,000/year tuition waiver',
    amountEurMonthly: 833,
    coverage: 'Full tuition reduction to €200/year based on academic merit',
    eligibilityNationalities: 'all',
    eligibilityMinGpa: 3.5,
    eligibilityFields: ['Computer Science', 'Engineering'],
    eligibilityDegreeLevels: ['masters'],
    applicationDeadline: '2026-01-20',
    applicationUrl: 'https://www.polimi.it/scholarships',
    linkedUniversityIds: ['uni-10']
  },
  {
    id: 'sch-10',
    name: 'Finnish Government Scholarship',
    provider: 'Finnish National Agency for Education',
    type: 'stipend',
    amountDescription: '€1,500/month stipend',
    amountEurMonthly: 1500,
    coverage: 'Monthly living allowance for the duration of studies',
    eligibilityNationalities: 'all',
    eligibilityMinGpa: 3.2,
    eligibilityFields: ['Computer Science', 'Engineering'],
    eligibilityDegreeLevels: ['masters', 'phd'],
    applicationDeadline: '2026-02-28',
    applicationUrl: 'https://www.oph.fi/en/scholarships',
    linkedUniversityIds: ['uni-11']
  }
];

export const europeanCountries = [
  'Germany', 'Netherlands', 'Austria', 'Hungary', 'Czech Republic',
  'Poland', 'France', 'Italy', 'Spain', 'Sweden', 'Finland',
  'Denmark', 'Norway', 'Belgium', 'Switzerland', 'Ireland',
  'Portugal', 'Greece', 'Romania', 'Croatia'
];

export const fieldsOfStudy = [
  'Computer Science', 'Engineering', 'Business Administration',
  'Medicine', 'Law', 'Arts & Humanities', 'Natural Sciences',
  'Social Sciences', 'Architecture', 'Economics', 'Mathematics',
  'Physics', 'Chemistry', 'Biology', 'Psychology', 'Education'
];

export const allNationalities = [
  'Afghanistan', 'Albania', 'Algeria', 'Argentina', 'Australia', 'Austria',
  'Bangladesh', 'Belgium', 'Brazil', 'Canada', 'China', 'Colombia',
  'Czech Republic', 'Denmark', 'Egypt', 'Ethiopia', 'Finland', 'France',
  'Germany', 'Ghana', 'Greece', 'Hungary', 'India', 'Indonesia',
  'Iran', 'Iraq', 'Ireland', 'Italy', 'Japan', 'Jordan', 'Kenya',
  'Lebanon', 'Libya', 'Malaysia', 'Mexico', 'Morocco', 'Nepal',
  'Netherlands', 'Nigeria', 'Norway', 'Pakistan', 'Palestine',
  'Philippines', 'Poland', 'Portugal', 'Romania', 'Russia',
  'Saudi Arabia', 'South Korea', 'Spain', 'Sri Lanka', 'Sudan',
  'Sweden', 'Switzerland', 'Syria', 'Tanzania', 'Thailand',
  'Tunisia', 'Turkey', 'Uganda', 'Ukraine', 'United Arab Emirates',
  'United Kingdom', 'United States', 'Vietnam', 'Yemen', 'Zimbabwe'
];

export const languages = [
  'English', 'German', 'French', 'Dutch', 'Spanish', 'Italian',
  'Swedish', 'Danish', 'Finnish', 'Norwegian', 'Polish', 'Czech',
  'Hungarian', 'Portuguese', 'Arabic', 'Turkish', 'Hindi', 'Urdu',
  'Bengali', 'Chinese'
];
